# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-wissem-pjs"
BBFILE_PATTERN_meta-wissem-pjs = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-wissem-pjs = "6"

LAYERDEPENDS_meta-wissem-pjs = "core"
LAYERSERIES_COMPAT_meta-wissem-pjs = "walnascar"
